#!/usr/bin/env node
/**
 * Build-time map converter
 * Converts Tiled JSON maps to TypeScript modules for AI Town
 * Now with semantic map support from generative_agents CSV files!
 *
 * Usage:
 *   npm run convert-map <json-path> [layer-filter...]
 *
 * Examples:
 *   npm run convert-map public/assets/the_ville/map.json
 *   npm run convert-map public/assets/the_ville/map.json "Ground" "Building" "Wall"
 */

import * as fs from 'fs';
import * as path from 'path';
import { convertTiledMapToAITown } from '../data/convertTiledMap';

// Get arguments
const jsonPathArg = process.argv[2];
const layerFilterArgs = process.argv.slice(3);

if (!jsonPathArg) {
  console.error('Usage: npm run convert-map <json-path> [layer-filter...]');
  console.error('');
  console.error('Examples:');
  console.error('  npm run convert-map public/assets/the_ville/map.json');
  console.error('  npm run convert-map public/assets/my_map/map.json "Ground" "Buildings"');
  process.exit(1);
}

const jsonPath = path.resolve(process.cwd(), jsonPathArg);
const layerFilter = layerFilterArgs.length > 0 ? layerFilterArgs : undefined;

console.log(`\n${'='.repeat(60)}`);
console.log(`AI-Town Map Converter with Semantic Support`);
console.log(`${'='.repeat(60)}\n`);
console.log(`Converting map from: ${jsonPath}`);
if (layerFilter) {
  console.log(`Layer filter: ${layerFilter.join(', ')}`);
}

// Load Tiled JSON
if (!fs.existsSync(jsonPath)) {
  console.error(`Error: File not found: ${jsonPath}`);
  process.exit(1);
}

const tiledMapContent = fs.readFileSync(jsonPath, 'utf-8');
const tiledMap = JSON.parse(tiledMapContent);

// Detect map name from path
const mapName = path.basename(path.dirname(jsonPath));
const assetsUrlPrefix = '/ai-town/assets/';

console.log(`\nMap Information:`);
console.log(`  Name: ${mapName}`);
console.log(`  Size: ${tiledMap.width}x${tiledMap.height}`);
console.log(`  Tile Size: ${tiledMap.tilewidth}x${tiledMap.tileheight}px`);
console.log(`  Layers: ${tiledMap.layers.length}`);

// Convert the map using our conversion function
console.log(`\n${'─'.repeat(60)}`);
console.log(`Converting map...`);
console.log(`${'─'.repeat(60)}\n`);

const serializedMap = convertTiledMapToAITown(
  tiledMap,
  mapName,
  assetsUrlPrefix,
  layerFilter,
  true // Enable semantic map parsing
);

// Generate TypeScript module
const output = `// Generated map
// DO NOT EDIT THIS FILE MANUALLY
// Generated by: npm run convert-map ${jsonPathArg}
// Source: ${jsonPath}

import type { SerializedWorldMap } from '../../convex/aiTown/worldMap';

export const mapData: SerializedWorldMap = ${JSON.stringify(serializedMap, null, 2)};

export default mapData;
`;

// Write output file
const outputPath = path.resolve(process.cwd(), `data/maps/${mapName}.ts`);
const outputDir = path.dirname(outputPath);

if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputPath, output, 'utf-8');

// Print summary
console.log(`\n${'='.repeat(60)}`);
console.log(`✓ Map converted successfully!`);
console.log(`${'='.repeat(60)}\n`);
console.log(`Output: ${outputPath}`);
console.log(``);
console.log(`Summary:`);
console.log(`  Map Size: ${serializedMap.width}x${serializedMap.height}`);
console.log(`  Tilesets: ${serializedMap.tilesets?.length || 0}`);
console.log(`  Rendered Layers: ${serializedMap.bgTiles?.length || 0}`);
console.log(`  Collision Layers: ${serializedMap.objectTiles?.length || 0}`);
console.log(`  Exterior Ground: ${serializedMap.exteriorGroundLayer ? 'Yes' : 'No'}`);
console.log(`  Semantic Map: ${serializedMap.semanticMap ? 'Yes ✓' : 'No'}`);

if (serializedMap.semanticMap) {
  console.log(`\n  📍 Semantic Map Details:`);

  const addressCount = serializedMap.semanticMap.addressTiles.length;
  console.log(`    Total Addresses: ${addressCount}`);

  // Count addresses by type
  const sectorAddresses = serializedMap.semanticMap.addressTiles.filter(
    e => !e.address.includes('<spawn_loc>') && (e.address.match(/:/g) || []).length === 1
  );
  const arenaAddresses = serializedMap.semanticMap.addressTiles.filter(
    e => !e.address.includes('<spawn_loc>') && (e.address.match(/:/g) || []).length === 2
  );
  const objectAddresses = serializedMap.semanticMap.addressTiles.filter(
    e => !e.address.includes('<spawn_loc>') && (e.address.match(/:/g) || []).length === 3
  );
  const spawnAddresses = serializedMap.semanticMap.addressTiles.filter(
    e => e.address.includes('<spawn_loc>')
  );

  console.log(`      - Sectors: ${sectorAddresses.length}`);
  console.log(`      - Arenas: ${arenaAddresses.length}`);
  console.log(`      - Game Objects: ${objectAddresses.length}`);
  console.log(`      - Spawn Locations: ${spawnAddresses.length}`);

  // Count tiles with semantic data
  let tilesWithSemantics = 0;
  let tilesWithArena = 0;
  let tilesWithObjects = 0;

  for (const row of serializedMap.semanticMap.tiles) {
    for (const tile of row) {
      if (tile.sector || tile.arena || tile.game_object || tile.spawning_location) {
        tilesWithSemantics++;
      }
      if (tile.arena) tilesWithArena++;
      if (tile.game_object) tilesWithObjects++;
    }
  }

  const totalTiles = serializedMap.width * serializedMap.height;
  const coveragePercent = ((tilesWithSemantics / totalTiles) * 100).toFixed(1);

  console.log(`\n    Coverage:`);
  console.log(`      - ${tilesWithSemantics} / ${totalTiles} tiles (${coveragePercent}%)`);
  console.log(`      - ${tilesWithArena} tiles in arenas`);
  console.log(`      - ${tilesWithObjects} tiles with objects`);

  // Show sample addresses by category
  console.log(`\n    Sample Addresses:`);

  if (sectorAddresses.length > 0) {
    console.log(`      Sectors:`);
    sectorAddresses.slice(0, 2).forEach((entry) => {
      console.log(`        • ${entry.address} (${entry.coordinates.length} tiles)`);
    });
  }

  if (arenaAddresses.length > 0) {
    console.log(`      Arenas:`);
    arenaAddresses.slice(0, 3).forEach((entry) => {
      console.log(`        • ${entry.address} (${entry.coordinates.length} tiles)`);
    });
  }

  if (objectAddresses.length > 0) {
    console.log(`      Game Objects:`);
    objectAddresses.slice(0, 3).forEach((entry) => {
      console.log(`        • ${entry.address} (${entry.coordinates.length} tiles)`);
    });
  }

  if (spawnAddresses.length > 0) {
    console.log(`      Spawn Locations:`);
    spawnAddresses.slice(0, 3).forEach((entry) => {
      console.log(`        • ${entry.address} (${entry.coordinates.length} tiles)`);
    });
  }

  // Show sample tile semantics at specific coordinates
  console.log(`\n    Sample Tile Data:`);
  let samplesShown = 0;
  for (let y = 0; y < serializedMap.height && samplesShown < 3; y++) {
    for (let x = 0; x < serializedMap.width && samplesShown < 3; x++) {
      const tile = serializedMap.semanticMap.tiles[y][x];
      if (tile.game_object) {
        console.log(`      Tile (${x}, ${y}):`);
        console.log(`        World: "${tile.world}"`);
        if (tile.sector) console.log(`        Sector: "${tile.sector}"`);
        if (tile.arena) console.log(`        Arena: "${tile.arena}"`);
        if (tile.game_object) console.log(`        Object: "${tile.game_object}"`);
        if (tile.spawning_location) console.log(`        Spawn: "${tile.spawning_location}"`);
        samplesShown++;
      }
    }
  }
}

console.log(``);
console.log(`Next steps:`);
console.log(`1. Import in data/mapConfig.ts:`);
console.log(`   import { mapData as ${mapName}Map } from './maps/${mapName}';`);
console.log(``);
console.log(`2. Add to AVAILABLE_MAPS:`);
console.log(`   ${mapName}: {`);
console.log(`     name: 'Your Map Name',`);
console.log(`     data: ${mapName}Map,`);
console.log(`   },`);
console.log(``);
